allowBuilds:
  core-js: false
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  vue-demi: false
  workerd: false
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - msw
  - protobufjs
  - sharp
  - vue-demi
  - workerd
